services:
  - type: web
    name: meeting-room-web
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: USE_WEBHOOK
        value: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TELEGRAM_INIT_DATA_MAX_AGE
        value: 3600

  - type: worker
    name: meeting-room-bot
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile.bot
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: USE_WEBHOOK
        value: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: ADMIN_ID
        sync: false
